### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by Amitabitbul** [IsaacSomething/stackoverflow-view-vscode#19]
Hi,
I'm trying to rebuild the extension and change the design a bit.
Can share with us some instructions on how to build it?

It requires a model called - static-models, do you have an example of this file?

Thanks! @IsaacSomething

**Comment by IsaacSomething** [comment]
Hey

Sorry this was written quite a while ago and i dont have access to the local files (not in my country at the moment). If i am not mistaken that static-models was just a little help file with details to the stack overflow information that you should get when you register to use their API. 

You could replace `uriSegments.baseUri` with the uri that you get for your application development. I didnt include the file itself because anyone could then use that uri to make calls which would then reflect on my account. 

If i get some time i will try create a demo file that represents the details from that file (cant promise anything but i will try)

**Comment by Amitabitbul** [comment]
> Hey
> 
> Sorry this was written quite a while ago and i dont have access to the local files (not in my country at the moment). If i am not mistaken that static-models was just a little help file with details to the stack overflow information that you should get when you register to use their API.
> 
> You could replace `uriSegments.baseUri` with the uri that you get for your application development. I didnt include the file itself because anyone could then use that uri to make calls which would then reflect on my account.
> 
> If i get some time i will try create a demo file that represents the details from that file (cant promise anything but i will try)

Thanks, very much appreciate it!
And it looks like the files have some issues with the names and more.

Do you have a buildable source code? there is another way to reach out? Its for a project I'm trying to build for the next week.

**Comment by IsaacSomething** [comment]
I can try, but like i said, im currently not in my country at the moment so I dont have the local files with me. I think there might be an issue with the project though because it was written in an older version of svelte.

I would suggest just using the repo as a template and use the latest svelte things. If i can remember it is not too difficult, I remember following the official svelte documentation and the vscode extension documentation.

I would really like to have kept this repo up to date but i have had no time to spend on it :(

**Comment by Amitabitbul** [comment]
> I can try, but like i said, im currently not in my country at the moment so I dont have the local files with me. I think there might be an issue with the project though because it was written in an older version of svelte.
> 
> I would suggest just using the repo as a template and use the latest svelte things. If i can remember it is not too difficult, I remember following the official svelte documentation and the vscode extension documentation.
> 
> I would really like to have kept this repo up to date but i have had no time to spend on it :(

Understood, Thanks!
It's a great repo!

I'm not closing it, feel free to close the issue yourself if you haven't found a time to update :)
